plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "D:\\kerjaan\\BRIN\\07_pretes_post_tes\\FINAL_SIAP_KIRIM_2026-10-14"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]